language: clojure
lein: lein2
script: lein2 test
branches:
  only:
    - develop
    - master
jdk:
  - openjdk7
env:
  global:
    - secure: "TJuL7paiT3NwSZjLPAFQpaZTIZ8eIqk+8+lJfg34xqmTRzMnoh6YAUgTZaaO1dvAAFu/l2v3RyQjb6R6BYBqpkUwSE6YZd18gnxcpsvqsPlquRBXM0rawp5c+GaBb2+0EnZEWEvPS8Pggq+fGitwtZ0cAGpdr23NFsmhLatVKVQ="